server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-auth-route
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: oauth2-route
          uri: lb://user-service
          predicates:
            - Path=/oauth2/**,/login/**
          filters:
            - StripPrefix=0

        - id: measurement-route
          uri: lb://measurement-service
          predicates:
            - Path=/api/convert/**,/api/v1/quantities/**
          filters:
            - StripPrefix=0

        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: your-very-long-secret-key-for-quantity-measurement-app-uc18

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
